### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by anwir-prota** [y7u/-#1]
hi

**Comment by y7u** [comment]
> What’s Zets tag on Discord

I dont know. I dont use discord

**Comment by y7u** [comment]
> What’s Zets tag on Discord

you know what happened to him?

**Comment by zet-sec** [comment]
@anwir-prota Hello, Contact me on Discord: Fibonacci#8011

**Comment by zet-sec** [comment]
@y7u I got banned on Telegram fuck
